sudo: false
language: java
jdk:
- oraclejdk8

cache:
  directories:
    - "$HOME/google-cloud-sdk/"
script:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
    
before_deploy:
  - mv target/healthcare-1.0.jar target/healthcare.jar

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: secret.json
  project: healthcare-196408
  file: target/healthcare.jar
before_install:
- chmod +x mvnw
- openssl aes-256-cbc -K $encrypted_07ec618bb998_key -iv $encrypted_07ec618bb998_iv
  -in secret.json.enc -out secret.json -d
