language: java
jdk:
- oraclejdk8
deploy:
  provider: gae
  keyfile: secret.json
  project: healthcare-196408
before_install:
- openssl aes-256-cbc -K $encrypted_b4195608ac89_key -iv $encrypted_b4195608ac89_iv -in secret.json.enc -out secret.json -d
